name: Create release pull request or publish new release

on:
  push:
    branches:
      - main
    paths:
      - '.changeset/**'

jobs:
  release:
    name: Create release pull request or publish new release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install

      # @link https://github.com/changesets/action
      - name: Create release PR and changelog or publish
        uses: changesets/action@v1.2.2
        with:
          commit: 'chore: update versions'
          title: 'chore: update versions'
          publish: pnpm ci:publish
        env:
          HOME: ${{ github.workspace }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
